// <auto-generated />
using CoinFlipper.SwissArmy.Infrastructure.Repositories.Postgres.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoinFlipper.SwissArmy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoinFlipper.SwissArmy.Infrastructure.Repositories.Models.SentenceDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sentence");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Satoshi Nakamoto",
                            Sentence = "If you don’t believe it or don’t get it, I don’t have the time to try to convince you, sorry."
                        },
                        new
                        {
                            Id = 2,
                            Author = "",
                            Sentence = "Scams always pump the hardest in a risk-on environment."
                        },
                        new
                        {
                            Id = 3,
                            Author = "",
                            Sentence = "A clear mind is a foundation of a good trade."
                        },
                        new
                        {
                            Id = 4,
                            Author = "",
                            Sentence = "Knowledge opens a lot of doors."
                        },
                        new
                        {
                            Id = 5,
                            Author = "",
                            Sentence = "Little of something is greater than all of nothing."
                        },
                        new
                        {
                            Id = 6,
                            Author = "",
                            Sentence = "Learn at your first bull run, retire at second."
                        },
                        new
                        {
                            Id = 7,
                            Author = "T. Harv Eker",
                            Sentence = "How you do anything is how you do everything."
                        },
                        new
                        {
                            Id = 8,
                            Author = "",
                            Sentence = "What you don't use you lose."
                        },
                        new
                        {
                            Id = 9,
                            Author = "",
                            Sentence = "All good things come to those who wait."
                        },
                        new
                        {
                            Id = 10,
                            Author = "",
                            Sentence = "The bull walks up the stairs and the bear jumps out the window."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Sheryl Sandberg",
                            Sentence = "Done is better than perfect."
                        },
                        new
                        {
                            Id = 12,
                            Author = "Socrates",
                            Sentence = "The secret to change is to focus all of your energy not on fighting the old, but building the new."
                        },
                        new
                        {
                            Id = 13,
                            Author = "",
                            Sentence = "Man becomes slave of his own repeated actions."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Benjamin Franklin",
                            Sentence = "An investment in knowledge pays the best interest."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Carlos Slim Helu",
                            Sentence = "With a good perspective on history, we can have a better understanding of the past and present, and thus a clear vision of the future."
                        },
                        new
                        {
                            Id = 16,
                            Author = "Mellody Hobson",
                            Sentence = "The biggest risk of all is not taking one."
                        },
                        new
                        {
                            Id = 17,
                            Author = "Peter Lynch",
                            Sentence = "Know what you own, and know why you own it."
                        },
                        new
                        {
                            Id = 18,
                            Author = "Warren Buffett",
                            Sentence = "Wide diversification is only required when investors do not understand what they are doing."
                        },
                        new
                        {
                            Id = 19,
                            Author = "Peter Thiel",
                            Sentence = "The most contrarian thing of all is not to oppose the crowd but to think for yourself."
                        },
                        new
                        {
                            Id = 20,
                            Author = "Aya Laraya",
                            Sentence = "When you invest, you are buying a day that you don’t have to work."
                        },
                        new
                        {
                            Id = 21,
                            Author = "Jim Rohn",
                            Sentence = "Formal education will make you a living; self-education will make you a fortune."
                        },
                        new
                        {
                            Id = 22,
                            Author = "Grant Cardone",
                            Sentence = "Investing puts money to work. The only reason to save money is to invest it."
                        },
                        new
                        {
                            Id = 23,
                            Author = "",
                            Sentence = "Do not put all your eggs in one basket."
                        },
                        new
                        {
                            Id = 24,
                            Author = "Mark Twain",
                            Sentence = "Courage is note the lack of fear. It is acting in spite of it."
                        },
                        new
                        {
                            Id = 25,
                            Author = "Steve Clark",
                            Sentence = "Do more of what works and less of what doesn’t."
                        },
                        new
                        {
                            Id = 26,
                            Author = "Warren Buffett",
                            Sentence = "Risk comes from not knowing what you are doing."
                        },
                        new
                        {
                            Id = 27,
                            Author = "Warren Buffett",
                            Sentence = "If you cannot control your emotions, you can’t control your money."
                        },
                        new
                        {
                            Id = 28,
                            Author = "Marty Schwartz",
                            Sentence = "Learn to take losses. The most important thing in making money is not letting your losses get out of hand."
                        },
                        new
                        {
                            Id = 29,
                            Author = "",
                            Sentence = "Always check correlations to see bigger picture."
                        },
                        new
                        {
                            Id = 30,
                            Author = "",
                            Sentence = "Price is never \"too high\" or \"too low\"."
                        },
                        new
                        {
                            Id = 31,
                            Author = "",
                            Sentence = "Ping-Pong till you wrong."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
