version: '3.8'

networks:
 coinflipper:

volumes:
  postgres:
  pgadmin:
  seq:
  redis:
   
services:
  seq:
    image: datalust/seq:2023.4
    ports:
      - "6001:80"
    environment:
      - ACCEPT_EULA=Y  
    networks:
      coinflipper:  

  pgadmin4:
    image: dpage/pgadmin4:8.0
    ports:
        - "6002:80"
    volumes:
        - pgadmin:/var/lib/pgadmin
        - ./Scripts/Configs/registerServer.json:/registerServer.json
    environment:
      PGADMIN_DEFAULT_EMAIL: "coinflipper8@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "coin"
      PGADMIN_SERVER_JSON_FILE: "/registerServer.json"
    networks:
      coinflipper:    

  postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data:z
      - ./Scripts/Configs/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: coinflipper8
      POSTGRES_PASSWORD: coin
    ports:
      - "6003:5432"
    networks:
      coinflipper:    

  keycloak:
    image: jboss/keycloak:16.1.1
    volumes:
      - ./Scripts/Configs/coinFlipperKeycloakRealm.json:/tmp/coinFlipperKeycloakRealm.json
    hostname: keycloak
    environment:
      JDBC_PARAMS: "useSSL=false"
      KEYCLOAK_USER: "coinflipper8"
      KEYCLOAK_PASSWORD: "coin"
      DB_VENDOR: "postgres"
      DB_ADDR: "postgres"
      DB_USER: "coinflipper8"
      DB_PASSWORD: "coin"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      KEYCLOAK_IMPORT: /tmp/coinFlipperKeycloakRealm.json
    ports:
      - 6004:8080
    networks:
      coinflipper:   

  redis:
    image: redis:7.2.4
    volumes:
      - redis:/data
    ports:
      - "6005:6379"
    command: redis-server --appendonly yes  
    networks:
      coinflipper:   


  tracer:
    image: coinflipper-tracer:latest
    ports:
      - "6010:80"
    depends_on:
      - postgres  
      - redis
    environment:
      App__Port: "80"
      Logger__Seq__Url: "http://seq:80"
      Postgres__ConnectionString: "Host=postgres;Port=5432;User Id=coinflipper8;Password=coin;Database=Tracer;Enlist=true;Include Error Detail=true;"
      Redis__Address: "redis:6379"
    networks:
      coinflipper:

  notification:
    image: coinflipper-notification:latest
    ports:
      - "6011:80"
    environment:  
      App__Port: "80"
      Logger__Seq__Url: "http://seq:80"
    networks:
      coinflipper:

  swissArmy:
    image: coinflipper-swissarmy:latest
    ports:
      - "6012:80"
    depends_on:
      - postgres
    environment:
      App__Port: "80"
      Logger__Seq__Url: "http://seq:80"
      Postgres__ConnectionString: "Host=postgres;Port=5432;User Id=coinflipper8;Password=coin;Database=SwissArmy;Enlist=true;Include Error Detail=true;"
    networks:
      coinflipper:       

  access:
    image: coinflipper-access:latest
    ports:
      - "6013:80"
    depends_on:
      - postgres
    environment:
      App__Port: "80"
      Logger__Seq__Url: "http://seq:80"
    networks:
      coinflipper:    
